export enum TxButtonType {
  QUERY = 'QUERY',
  RPC = 'RPC',
  SIGNEDTX = 'SIGNED-TX',
  UNISGNEDTX = 'UNSIGNED-TX',
  SUDOTX = 'SUDO-TX',
  UNCHECKEDSUDOTX = 'UNCHECKED-SUDO-TX',
  CONSTANT = 'CONSTANT',
}
